config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: '/dashboard'

    resources :payment_methods, only: %i[new create show destroy index], shallow: true do
      post 'enable', on: :member
      post 'disable', on: :member
    end
  end

  root 'home#index'
  resources :companies, only: %i[edit update show] do
    get '/payment_settings', to: 'companies#payment_settings'
    put '/cancel_registration', to: 'companies#cancel_registration'
  end

  resources :pix_settings, only: %i[new create]

  resources :boleto_settings, only: %i[new create]

  resources :credit_card_settings, only: %i[new create]

  namespace :api do
    namespace :v1 do
      resources :customer, only: %i[index show create]
      resources :pix_settings, only: %i[index show]
      resources :boleto_settings, only: %i[index show]
      resources :credit_card_settings, only: %i[index show]
      resources :customer_payment_method, only: %i[index show create]
    end
  end
end

app/views/shared/_admin_navbar.html.erb
<nav class="bg-white border-b-2 border-purple-900">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
  <div class="relative flex items-center justify-start space-x-4 h-16">
      <% if current_admin %>
      <div class="text-pink-900 font-medium">Métodos de pagamento > </div>
        <%= link_to 'Criar novo', new_admin_payment_method_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
        <%= link_to 'Listar todos', admin_payment_methods_path, class: "bg-white hover:text-red-900 text-pink-900 font-medium py-1 px-4 border border-pink-900 rounded focus:outline-none" %>
      <% end %>
      <div>
  </div>
</nav>

app/views/shared/_dashboard_navbar.html.erb
<header class="text-gray-600 body-font bg-white">
    <nav class="flex justify-start mb-4 border-b border-gray-600">
      <% if current_admin %>
        <%= link_to 'Criar método de pagamento', new_admin_payment_method_path, class: "mx-5 py-2" %>
        <%= link_to 'Listar métodos de pagamentos', admin_payment_methods_path, class: "mx-5 py-2" %>
      <% end %>
    </nav>
</header>

app/views/shared/_navbar.html.erb
<nav class="bg-purple-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
  <div class="relative flex items-center justify-between h-16">
    <div class="flex title-font font-medium items-center text-gray-900 ml-10">
      <svg class="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
      </svg>
      <%= link_to 'PagaPaga', root_path, class: "ml-3 text-xl text-white font-semibold transition duration-100 transition transform hover:scale-105 motion-reduce:transition-none" %>
    </div>

    <div>
      <% if current_user %>
      <div class="md:flex items-center mr-10">
        <span class="text-white text-medium">
          %= current_user.email %>
        </span>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "py-4 px-2 text-gray-500 font-medium hover:text-purple-800 transition duration-300" %>
        </div>
      <% elsif current_admin %>
        <span class="text-white text-medium">
          <%= current_admin.email %>
        </span>
        <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300 mr-10" %>
      <% else %>
        <div class="md:flex items-center mr-10">
          <%= link_to 'Cadastre-se', new_user_registration_path, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300" %>
          <%= link_to 'Entrar', new_user_session_path, class: "py-4 px-2 text-white font-medium hover:underline transition duration-300" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>