config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: '/dashboard'

    resources :payment_methods, only: %i[new create show destroy index], shallow: true do
      post 'enable', on: :member
      post 'disable', on: :member
    end
  end

  root 'home#index'
  resources :companies, only: %i[edit update show] do
    get '/payment_settings', to: 'companies#payment_settings'
    put '/cancel_registration', to: 'companies#cancel_registration'
  end

  resources :pix_settings, only: %i[new create]

  resources :boleto_settings, only: %i[new create]

  resources :credit_card_settings, only: %i[new create]

  namespace :api do
    namespace :v1 do
      resources :customer, only: %i[index show create]
      resources :pix_settings, only: %i[index show]
      resources :boleto_settings, only: %i[index show]
      resources :credit_card_settings, only: %i[index show]
      resources :customer_payment_method, only: %i[index show create]
    end
  end
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :pix_settings, dependent: :destroy
  has_many :credit_card_settings, dependent: :destroy
  has_many :boleto_settings, dependent: :destroy

  has_one_attached :icon
  enum status: { enabled: 5, disabled: 10 }
  enum type_of: { pix: 0, boleto: 5, credit_card: 10 }

  validates :name, :fee, :maximum_fee, :icon, presence: true
  validates :type_of, inclusion: { in: type_ofs.keys }

  def self.query_for_enabled
    PaymentMethod.where(status: :enabled)
  end

  def self.human_type_of_name(type_of_key)
    PaymentMethod.human_attribute_name("type_of.#{type_of_key}")
  end

  def self.types
    PaymentMethod.type_ofs.keys
  end

  def self.payment_types_dropdown
    type_keys = PaymentMethod.type_ofs.keys
    dropdown_list = []
    type_keys.each do |type_key|
      dropdown_list << [PaymentMethod.human_type_of_name(type_key), type_key]
    end

    dropdown_list
  end

  def self.payment_methods_by_type_dropdown(payment_type)
    payment_methods = PaymentMethod.where(type_of: payment_type, status: 'enabled')
    dropdown_list = []
    payment_methods.each do |payment_method|
      dropdown_list << [payment_method.name, payment_method.id]
    end

    dropdown_list
  end
end

app/controllers/admin/payment_methods_controller.rb
class Admin
  class PaymentMethodsController < ApplicationController
    before_action :authenticate_users!
    before_action :authenticate_admin!, only: %i[new create show index disable enable]

    def index
      @payment_methods = PaymentMethod.all
    end

    def show
      @payment_method = PaymentMethod.find(params[:id])
    end

    def new
      @payment_method = PaymentMethod.new
      @payment_types_dropdown = PaymentMethod.payment_types_dropdown
    end

    def create
      @payment_method = PaymentMethod.new(payment_method_params)
      @payment_types_dropdown = PaymentMethod.payment_types_dropdown

      if @payment_method.save
        redirect_to [:admin, @payment_method]
      else
        render :new
      end
    end

    def disable
      @payment_method = PaymentMethod.find(params[:id])
      @payment_method.disabled!

      redirect_to [:admin, @payment_method]
    end

    def enable
      @payment_method = PaymentMethod.find(params[:id])
      @payment_method.enabled!

      redirect_to [:admin, @payment_method]
    end

    private

    def payment_method_params
      params.require(:payment_method).permit(:name, :fee, :maximum_fee, :icon)
    end
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :authenticate_users!
  before_action :authenticate_admin!, only: %i[new create]

  def show
    @payment_method = PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = PaymentMethod.new
    @payment_types_dropdown = PaymentMethod.payment_types_dropdown
  end

  def create
    @payment_method = PaymentMethod.new(payment_method_params)
    @payment_types_dropdown = PaymentMethod.payment_types_dropdown

    if @payment_method.save
      redirect_to @payment_method
    else
      render :new
    end
  end

  private

  def payment_method_params
    params
      .require(:payment_method)
      .permit(
        :name,
        :fee,
        :maximum_fee,
        :icon,
        :type_of
      )
  end
end

app/views/admin/payment_methods/_payment_method.html.erb
<div class="flex border lg:w-1/3 h-30 max-w-ms mx-10 my-4 rounded-lg overflow-hidden">
  <% if payment_method.icon.attached? %>
    <div class="flex items-center justify-center w-28 h-30 border-r p-1">
      <%= image_tag "#{payment_method.icon.filename}" %>
    </div>
  <% end %>
  <div class="p-2">
    <div class="px-4 text-purple-900 font-semibold hover:text-purple-800 transition duration-300">
      <%= link_to payment_method.name, admin_payment_method_path(payment_method.id) %>
    </div>
    <p class="pl-4 text-gray-700 font-medium">
      Taxa: <%= payment_method.fee %> %
    </p">
    <p class="pl-4 text-gray-700 font-medium">
      Taxa máxima: <%= number_to_currency payment_method.maximum_fee %>
    </p>
    <p class="pl-4 text-gray-700 font-medium">Status: 
      <% if payment_method.enabled? %>
        <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= t payment_method.status %></span>
      <% else %>
        <span class="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= t payment_method.status %></span>
      <% end %>
    </p>
  </div>
</div>

app/views/admin/payment_methods/index.html.erb
<h1 class="text-center mt-5 text-2xl text-gray-800 font-medium">Métodos de Pagamentos</h1>

<% @payment_methods.each do |p| %>
    <%= render p %>
<% end %>

app/views/admin/payment_methods/new.html.erb
<h3 class="block text-gray-700 text-lg font-bold ml-5 my-2">Criar novo método de pagamento</h3>
<div class="max-w-xs m-5 text-center rounded-lg shadow-md p-4 bg-white border">

<%= form_with(model: [:admin, @payment_method]) do |f| %>
  <div class="form-m-w-content">
  <div class="mb-4">
    <%= f.label :name, class: "form-label"%>
    <%= f.text_field :name, class: "form-text-field" %> 

    <% @payment_method.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= f.label :fee, class: "form-label" %>
    <%= f.number_field :fee, class: "form-text-field" %>

    <% @payment_method.errors.full_messages_for(:fee).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= f.label :maximum_fee, class: "form-label" %>
    <%= f.number_field :maximum_fee, class: "form-text-field" %>
    
    <% @payment_method.errors.full_messages_for(:maximum_fee).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= f.label :type_of, class: "form-label" %>

    <%= 
    f.select :type_of, 
    @payment_types_dropdown,
    class: "form-text-field" 
    %>

    <% @payment_method.errors.full_messages_for(:type_of).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="flex flex-wrap mb-4">
    <%= f.label :icon, class: "form-label" %>
    <%= f.file_field :icon, class: "flex " %>

    <% @payment_method.errors.full_messages_for(:icon).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <%= f.submit 'Salvar', class: "form-submit-button" %>
  </div>
<% end %>
</div>

app/views/admin/payment_methods/show.html.erb
<div class="flex border lg:w-1/2 max-w-ms mx-10 my-4 rounded-lg overflow-hidden">
  <% if @payment_method.icon.attached? %>
    <div class="flex items-center justify-center w-28 h-auto border-r p-1">
      <%= image_tag "#{@payment_method.icon.filename}" %>
    </div>
  <% end %>

  <div class="p-2">
    <% if admin_signed_in? %>
      <p class="px-4 text-purple-900 font-semibold hover:text-purple-800 transition duration-300"">
        Nome: <%= @payment_method.name %>
      </p>
      <p class="pl-4 text-gray-700 font-medium">Taxa (%): <%= @payment_method.fee %></p>
      <p class="pl-4 text-gray-700 font-medium">Taxa máxima: <%= number_to_currency @payment_method.maximum_fee %></p>
      <p class="pl-4 text-gray-700 font-medium">Tipo: <%= PaymentMethod.human_type_of_name(@payment_method.name) %></p>
      <p class="pl-4 text-gray-700 font-medium">Status: 
        <% if @payment_method.enabled? %>
          <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= t @payment_method.status %></span>
        <% else %>
          <span class="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md"><%= t @payment_method.status %></span>
        <% end %>
      </p>
    <% end %>
  </div>
<div class="mx-5 lg:ml-20 my-auto">
<% if @payment_method.enabled? %>
    <%= link_to 'Desabilitar', disable_admin_payment_method_path(@payment_method.id), method: :post, class: "bg-white hover:text-red-700 text-red-600 font-bold mb-2 py-2 px-4 border border-red-600 rounded focus:outline-none" %>
<% elsif %>
  <%= link_to 'Habilitar', enable_admin_payment_method_path(@payment_method.id), method: :post, class: "bg-white hover:text-green-700 text-green-600 font-bold mb-2 py-2 px-4 border border-green-600 rounded focus:outline-none" %>
<% end %>
</div>
  
</div>