config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: '/dashboard'

    resources :payment_methods, only: %i[new create show destroy index], shallow: true do
      post 'enable', on: :member
      post 'disable', on: :member
    end
  end

  root 'home#index'
  resources :companies, only: %i[edit update show] do
    get '/payment_settings', to: 'companies#payment_settings'
    put '/cancel_registration', to: 'companies#cancel_registration'
  end

  resources :pix_settings, only: %i[new create]

  resources :boleto_settings, only: %i[new create]

  resources :credit_card_settings, only: %i[new create]

  namespace :api do
    namespace :v1 do
      resources :customer, only: %i[index show create]
      resources :pix_settings, only: %i[index show]
      resources :boleto_settings, only: %i[index show]
      resources :credit_card_settings, only: %i[index show]
      resources :customer_payment_method, only: %i[index show create]
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :pix_settings, dependent: :destroy
  has_many :credit_card_settings, dependent: :destroy
  has_many :boleto_settings, dependent: :destroy

  enum status: { incomplete: 0, pending: 10, accepted: 20, rejected: 30 }

  has_one :owner, -> { where owner: true },
          class_name: 'User', inverse_of: 'company', dependent: :destroy

  after_save :check_if_still_incomplete
  after_save :generate_token_if_accepted

  validates :cnpj, :legal_name, :billing_address, :billing_email,
            presence: true, on: :update
  validates :billing_email, private_email: true, on: :update
  validates :cnpj, cnpj: true, on: :update

  def payment_settings
    pix_settings + credit_card_settings + boleto_settings
  end

  def find_enabled_payment_setting_by_token(token)
    payment_settings.find do |ps|
      ps.enabled? && ps.payment_method.enabled? && ps.token == token
    end
  end

  # TODO: remover se não for utilizado
  def list_payment_methods
    pix_settings.map(&:payment_method) + credit_card_settings.map(&:payment_method) + 
    boleto_settings.map(&:payment_method)
  end

  def blank_all_info!
    self.cnpj = ''
    self.legal_name = ''
    self.billing_address = ''
    self.billing_email = ''
    self.status = :incomplete

    save(validate: false)
  end

  private

  def any_essential_info_blank?
    [cnpj, legal_name, billing_address, billing_email].all?(&:blank?)
  end

  def check_if_still_incomplete
    pending! if !any_essential_info_blank? && incomplete?
  end

  def accepted_but_no_token?
    token.blank? && accepted?
  end

  def generate_token_if_accepted
    return unless token.blank? && accepted?

    self.token = generate_token
    save!
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :redirect_empty_company_users, only: %i[edit update]
  before_action :find_company_and_authenticate_owner, only: %i[edit update cancel_registration]
  before_action :redirect_if_pending_company, only: %i[edit update]
  before_action :authenticate_company_user, only: %i[show]
  before_action :authenticate_user_company_accepted, only: %i[payment_settings]

  def show; end

  def edit; end

  def update
    if @company.update(edit_company_params)
      @company.pending! if @company.rejected?
      redirect_to @company, notice: t('.complete_success_notice')
    else
      render :edit
    end
  end

  def payment_settings
    @enabled_payment_methods = PaymentMethod.query_for_enabled
    @payment_settings = current_user.company.payment_settings
  end

  def cancel_registration
    @company.blank_all_info!

    redirect_to root_path
  end

  private

  def edit_company_params
    params.require(:company).permit(
      :legal_name,
      :cnpj,
      :billing_email,
      :billing_address
    )
  end
end

app/views/companies/edit.html.erb
<h2>
  <% if @company.incomplete? %>
    <%= t '.ask_to_complete_company' %>
  <% elsif @company.accepted? %>
    <%= t '.edit_company_message' %>
  <% end %>
</h2>

<% if @company.errors.any? %>
  <ul>
    <% @company.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @company, :url => company_path(@company), method: :patch do |f| %>
  <div>
    <%= f.label :legal_name %>
    <%= f.text_field :legal_name %>
  </div>
  <div>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div>
    <%= f.label :billing_address %>
    <%= f.text_field :billing_address %>
  </div>
  <div>
    <%= f.label :billing_email %>
    <%= f.text_field :billing_email %>
  </div>
  <%= f.submit t('common.submit') %>
<% end %>

app/views/companies/payment_settings.html.erb
<div>
    <% PaymentMethod.types.each do |payment_method_type| %>
        <span>
        <%= 
        link_to "#{t('.new_payment_setting_prefix')} #{PaymentMethod.human_type_of_name(payment_method_type).downcase}", 
        "/#{payment_method_type}_settings/new" 
        %>
        </span>
    <% end %>
</div>

<div>
  <% @payment_settings.each do |ps| %>
    <%= render partial: "payment_settings/#{ps.class}", locals: { payment_setting: ps } %>
  <% end %>
</div>

app/views/companies/show.html.erb
<% if current_user&.owns?(@company) %>
  <% if @company.pending? %>
    <%= link_to 'Cancelar pedido de registro', company_cancel_registration_path(@company, id: @company.id), method: :put %>
  <% else %>
    <%= link_to 'Editar dados', edit_company_path(@company) %>
  <% end %>
<% end %>

<div>
    <span><%= Company.human_attribute_name('status') %>: <%= Company.human_attribute_name("status.#{@company.status}") %></span>
</div>

<% if @company.accepted? %>
    <%= link_to t('.configure_payment'), company_payment_settings_path(@company) %>
<% end %>

<div>
    <dl>
        <dt><%= Company.human_attribute_name('legal_name') %>: </dt>
        <dd> <%= @company.legal_name %></dd>
        <dt><%= Company.human_attribute_name('cnpj') %>: </dt>
        <dd> <%= @company.cnpj %></dd>
        <dt><%= Company.human_attribute_name('billing_email') %>: </dt>
        <dd> <%= @company.billing_email %></dd>
        <dt><%= Company.human_attribute_name('billing_address') %>: </dt>
        <dd> <%= @company.billing_address %></dd>
        <% if @company.token %>
          <%= t('.token_explanation') %> <br>
          <dt><%= Company.human_attribute_name('token') %>: </dt>
          <dd> <%= @company.token %></dd>
        <% end %>
    </dl>
</div>